INSERT INTO ai_tools (name, description, category, subcategory, tags, keywords, use_cases, pricing_type, website_url, logo_url, rating, usage_count) VALUES

-- AI Humanizers & Writing
('Undetectable AI', 'Bypasses AI detectors by rewriting generated text into natural human-like prose.', 'Writing', 'AI Humanizers', 'humanizer, undetectable, bypass, rewriter', 'humanize AI text, AI humanizer, bypass turnitin, bypass gptzero, human writing, undetectable text, rewrite AI content', 'bypassing AI detection, humanizing generated essays, content rewrites', 'Freemium', 'https://undetectable.ai', 'https://logo.clearbit.com/undetectable.ai', 4.8, 450000),
('HideMyAI', 'Converts AI-generated drafts into humanized content tailored to pass modern detection models.', 'Writing', 'AI Humanizers', 'humanize, paraphraser, rewrite', 'AI text humanizer, hide my ai, rewrite AI content, undetectable writing, human-like writing, humanizer', 'blog post humanization, academic essay paraphrasing', 'Freemium', 'https://hidemy.ai', 'https://logo.clearbit.com/hidemy.ai', 4.6, 120000),
('BypassGPT', 'Advanced AI text transformer designed to make ChatGPT output undetectable.', 'Writing', 'AI Humanizers', 'gpt, humanizer, anti-detection', 'bypass gpt, ai humanizer, humanize ai, turnitin bypass, original text converter, humanizer', 'content creation, avoiding generic AI phrasing', 'Freemium', 'https://bypassgpt.ai', 'https://logo.clearbit.com/bypassgpt.ai', 4.7, 210000),
('Grammarly', 'AI-powered writing assistant focused on grammar checking, clarity, tone adjustment, and plagiarism detection.', 'Writing', 'Grammar & Tone', 'grammar, spell check, editor, writing assistant', 'grammar checker, AI writing, spell checker, essay editor, tone adjustment, sentence rewriter', 'editing essays, professional emails, proofreading articles', 'Freemium', 'https://grammarly.com', 'https://logo.clearbit.com/grammarly.com', 4.8, 2500000),

-- Presentation & PPT
('Gamma App', 'Generates full presentations, pitch decks, and documents from simple text prompts in seconds.', 'Presentation/PPT', 'Slide Generator', 'presentation, ppt, slides, pitch deck', 'PPT maker, presentation maker, AI presentation, slides generator, powerpoint AI, deck creator, PPT, slides', 'creating slide decks, making pitch presentations, instant PPT generation', 'Freemium', 'https://gamma.app', 'https://logo.clearbit.com/gamma.app', 4.9, 890000),
('Tome AI', 'AI story-driven presentation builder designed to create complete slides with custom images.', 'Presentation/PPT', 'Slide Generator', 'presentation, slides, storytelling', 'ppt creator, ai slides, powerpoint maker, presentation maker, interactive decks, PPT maker', 'business pitch decks, visual presentations, project proposals', 'Freemium', 'https://tome.app', 'https://logo.clearbit.com/tome.app', 4.7, 650000),

-- Coding & Development
('GitHub Copilot', 'AI pair programmer providing real-time code completion inside your favorite IDE.', 'Coding', 'Code Assistant', 'coding, developer, ide, autocomplete', 'coding assistant, code generator, github copilot, developer autocomplete, java python JS, programming assistant', 'inline code auto-completion, unit test generation, refactoring code', 'Paid', 'https://github.com/features/copilot', 'https://logo.clearbit.com/github.com', 4.9, 1500000),
('Cursor AI', 'AI-first code editor built on top of VS Code with codebase context awareness.', 'Coding', 'IDE & Editors', 'cursor, code editor, ide, programming', 'coding assistant, AI code editor, cursor ide, code generator, dev tool, programming AI', 'entire codebase editing, feature creation, automatic bug fixing', 'Freemium', 'https://cursor.com', 'https://logo.clearbit.com/cursor.com', 4.9, 420000),

-- Image, Resume & PDF
('Midjourney', 'High-quality text-to-image generator producing photorealistic artwork from prompts.', 'Image Generation', 'Text-to-Image', 'image, art, generation, photorealistic', 'image generator, text to image, ai art generator, midjourney, high res art, picture generator', 'generating concept art, stock photos, creative imagery', 'Paid', 'https://midjourney.com', 'https://logo.clearbit.com/midjourney.com', 4.9, 2000000),
('Kickresume AI', 'Creates ATS-friendly resumes and cover letters tailored to specific job descriptions.', 'Resume/Career', 'Resume Builder', 'resume, career, cv, cover letter', 'resume builder, AI resume, CV generator, cover letter maker, ATS resume builder, career AI', 'creating tailored job applications, optimizing resumes for ATS filters', 'Freemium', 'https://kickresume.com', 'https://logo.clearbit.com/kickresume.com', 4.8, 380000),
('ChatPDF', 'Allows you to chat with any PDF document, extract insights, and summarize key sections.', 'PDF/Documents', 'Document Query', 'pdf, summary, extraction, research', 'PDF AI, chat with pdf, document reader, pdf summarizer, extract pdf insights, read pdf', 'reading long papers, querying technical documentation, textbook summaries', 'Freemium', 'https://chatpdf.com', 'https://logo.clearbit.com/chatpdf.com', 4.8, 980000);